apiVersion: v1
appVersion: 1.17.1
description: Crossplane is an open source Kubernetes add-on that enables platform
  teams to assemble infrastructure from multiple vendors, and expose higher level
  self-service APIs for application teams to consume.
home: https://crossplane.io
icon: https://docs.crossplane.io/android-chrome-192x192.png
keywords:
- cloud
- infrastructure
- services
- application
- database
- cache
- bucket
- infra
- app
- ops
- gcp
- azure
- aws
- alibaba
- cloudsql
- rds
- s3
- azuredatabase
- asparadb
- gke
- aks
- eks
maintainers:
- email: info@crossplane.io
  name: Crossplane Maintainers
name: crossplane
version: 1.17.1-bb.0
annotations:
  bigbang.dev/applicationVersions: |
    - Crossplane: 1.17.1
  helm.sh/images: |
    - name: crossplane
      image: registry1.dso.mil/ironbank/opensource/crossplane/crossplane:v1.17.1
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    - [Crossplane Release Notes](https://github.com/crossplane/crossplane/releases/tag/v1.17.1)